# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e1582a6664ee43748d711e0c4b7e9cc26409921b14e6f34757311c918e20cb19fed6a2abfc29af202ba4381f5894af32fd93836394705fc7ed7aee7c1dd105
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>

test:
  secret_key_base: b4cf2db670fe13ef8be9090a5c96248c5f6ae1e9556d758214103e74824e9dd9593a60f767fd8baa70d30e1b66da83c69c74d834847d1cb53b29c78f4abc9003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
